# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: School-OS
description: Custom OS for school environment with essential tools.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    configurations:
      # System-wide Flathub packages (all users get these)
      - notify: true
        scope: system
        repo:
          title: Flathub (System)
          url: https://flathub.org/repo/flathub.flatpakrepo
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.onlyoffice.desktopeditors
          - org.libreoffice.LibreOffice

      # P3X OneNote from custom repository (system-wide)
      - notify: true
        scope: system
        repo:
          name: p3x-onenote
          title: P3X OneNote Repository
          url: https://flatpak.patrikx3.com/repo/p3x-onenote.flatpakrepo
        install:
          - com.patrikx3.onenote

      # User-scoped repositories (optional - for future user-specific apps)
      - scope: user
        notify: false

  - type: signing
